language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
      
sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit