language: php

php:
  - 7.0
  - hhvm

sudo: required

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate:refresh --seed

script: phpunit